name: skawa_components
version: 0.0.8+1

dependencies:
  angular2: ^3.1.0
  angular_components: ^0.5.1
  quiver: 0.25.0
dev_dependencies:
  sass_builder: ^0.1.0
  test: ^0.12.22+2
  angular_test: ^1.0.0-beta+3
  browser:
  angular_utility:
    git: https://github.com/skawa-universe/angular_utility.git
  html_unescape: ^0.1.5
dependency_overrides:
  sass:
    git:
      url: https://github.com/sass/dart-sass
      ref: e958477
transformers:
- angular2
- angular2/transform/reflection_remover:
   $include:
      - test/**_test.dart
- test/pub_serve:
   $include: test/**_test.dart
