name: skawa_components
version: 1.5.0
authors:
  - Harsányi Tamás (valakis) <tams.harsnyi@google.com>
  - Szepesházi András <szepeshazi@gmail.com>
  - Varga-Hali Daniel <https://github.com/daniel-v>
  - Farmasi Bulcsú <https://github.com/BulcsuFarmasi>
description:
  Additional components for AngularDart based on Material Design principles. These reusable components are not part of the official  Material Components library.
homepage: https://github.com/skawa-universe/skawa_components

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  angular: ^6.0.0
  angular_components: ^1.0.0
  sass_builder: ^2.1.2
  markdown: ^3.0.0
  js: ^0.6.1+1
  intl: ^0.16.0
  diff_match_patch: ^0.3.0
  meta: ^1.2.2

dev_dependencies:
  html_unescape: ^1.0.1+2
  mockito: ^4.0.0
  test: ^1.6.2
  angular_test: ^3.0.0
  pageloader: ^3.2.0
  build_config: ^0.4.1+1
  build_test: ^1.0.0
  build_runner: ^1.7.0
  build_web_compilers: ^2.0.0
