name: skawa_material_components
version: 1.3.1
authors:
  - Hars치nyi Tam치s (valakis) <tams.harsnyi@google.com>
  - Szepesh치zi Andr치s <szepeshazi@gmail.com>
  - Varga-Hali Daniel <https://github.com/daniel-v>
description:
  Additional Material Design components for AngularDart. Complements the official `angular_components` package.
homepage: https://github.com/skawa-universe/skawa_components

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha
  quiver: ^2.0.3
  sass_builder: ^2.1.2
  intl: ^0.15.7

dev_dependencies:
  test: ^1.6.2
  angular_test: ^2.3.0
  pageloader: ^3.2.0
  build_config: ^0.4.1+1
  build_test: ^0.10.7
  build_runner: ^1.7.0
  build_web_compilers: ^2.0.0
